# Generated by Django 4.0.10 on 2024-04-29 16:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombres del encargado')),
                ('apellidos', models.CharField(blank=True, max_length=300, null=True, verbose_name='Apellidos del encargado')),
                ('genero', models.CharField(blank=True, choices=[('1', 'Masculino'), ('2', 'Femenino'), ('3', 'Otro')], default=1, max_length=1, null=True, verbose_name='Género del encargado')),
                ('imag_perfil', models.ImageField(blank=True, null=True, upload_to='imagenes_usuarios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'], message='Sólo se permiten imágenes PNG')], verbose_name='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
