# Generated by Django 4.0.10 on 2024-05-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_location_options_remove_location_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='apellidos',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='genero',
            field=models.CharField(blank=True, choices=[('1', 'Masculino'), ('2', 'Femenino'), ('3', 'Otro')], default=1, max_length=1, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombre',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombres usuario'),
        ),
    ]
