# Generated by Django 4.0.10 on 2024-06-03 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_datospersonales_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='imag_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_usuarios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'], message='Sólo se permiten imágenes PNG')], verbose_name='Foto de perfil'),
        ),
    ]
