# Generated by Django 4.0.10 on 2024-06-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_datospersonales_imag_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='numero_telefono',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Número de Teléfono para el arduino'),
        ),
    ]
