# Generated by Django 4.0.10 on 2024-06-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de Teléfono para el arduino'),
        ),
    ]
