# Generated by Django 4.0.10 on 2024-06-03 21:52

from django.db import migrations, models
import mascota.models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_mascota_numero_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='numero_telefono',
            field=models.CharField(max_length=10, unique=True, validators=[mascota.models.validar_numero_telefono], verbose_name='Número de Teléfono'),
        ),
    ]
