# Generated by Django 4.0.10 on 2024-06-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_alter_mascota_numero_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='numero_telefono',
            field=models.IntegerField(max_length=10, unique=True, verbose_name='Número de Teléfono para el arduino'),
        ),
    ]
