# Generated by Django 4.0.10 on 2024-06-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0005_alter_mascota_numero_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='numero_telefono',
            field=models.IntegerField(unique=True, verbose_name='Número de Teléfono para el arduino'),
        ),
    ]
